-- 코드를 입력하세요
SELECT a.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK b INNER JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
            INNER JOIN BOOK_SALES s ON b.BOOK_ID = s.BOOK_ID
WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY a.AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY a.AUTHOR_ID, CATEGORY DESC