-- 코드를 입력하세요
SELECT EXTRACT(YEAR FROM SALES_DATE) AS YEAR, EXTRACT(MONTH FROM SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT(u.USER_ID)) AS USERS
FROM USER_INFO u INNER JOIN ONLINE_SALE o ON u.USER_ID = o.USER_ID
GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE), GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER