-- 코드를 작성해주세요

SELECT COUNT(fi.FISH_TYPE) AS FISH_COUNT, FISH_NAME
FROM FISH_INFO fi
INNER JOIN FISH_NAME_INFO fn ON fi.FISH_TYPE = fn.FISH_TYPE
GROUP BY fi.FISH_TYPE, FISH_NAME
ORDER BY FISH_COUNT DESC