-- 코드를 입력하세요
SELECT *
FROM (SELECT a.NAME, a.DATETIME
      FROM ANIMAL_INS a LEFT JOIN ANIMAL_OUTS o 
      ON a.ANIMAL_ID = o.ANIMAL_ID
      WHERE o.DATETIME IS NULL
      ORDER BY a.DATETIME)
WHERE ROWNUM < 4