-- 코드를 입력하세요
SELECT p.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT * PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT p INNER JOIN FOOD_ORDER o ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') LIKE '2022-05'
GROUP BY p.PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID