-- 코드를 입력하세요
SELECT FLAVOR
FROM (SELECT f.FLAVOR, f.TOTAL_ORDER + SUM(j.TOTAL_ORDER) AS TOTAL_ORDER
      FROM FIRST_HALF f INNER JOIN JULY j ON f.FLAVOR = j.FLAVOR
      GROUP BY f.FLAVOR, f.TOTAL_ORDER
      ORDER BY TOTAL_ORDER DESC)
WHERE ROWNUM <= 3
