-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, p.PT_NO, d.MCDP_CD, d.DR_NAME, APNT_YMD
FROM APPOINTMENT a INNER JOIN PATIENT p ON p.PT_NO = a.PT_NO
                   INNER JOIN DOCTOR d on a.MDDR_ID = d.DR_ID
WHERE d.MCDP_CD = 'CS' AND TO_CHAR(APNT_YMD, 'YYYY-MM-DD') = '2022-04-13' AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD
