-- 코드를 작성해주세요
SELECT e.EMP_NO, EMP_NAME, 
CASE WHEN AVG(SCORE) >= 96 THEN 'S'
     WHEN AVG(SCORE) >= 90 THEN 'A'
     WHEN AVG(SCORE) >= 80 THEN 'B'
     WHEN AVG(SCORE) < 80 THEN 'C'
     END 'GRADE',
CASE WHEN AVG(SCORE) >= 96 THEN SAL * 0.2
     WHEN AVG(SCORE) >= 90 THEN SAL * 0.15
     WHEN AVG(SCORE) >= 80 THEN SAL * 0.1
     WHEN AVG(SCORE) < 80 THEN SAL * 0
     END 'BONUS'
FROM HR_EMPLOYEES e INNER JOIN HR_DEPARTMENT d ON e.DEPT_ID = d.DEPT_ID
                    INNER JOIN HR_GRADE g ON e.EMP_NO = g.EMP_NO
GROUP BY e.EMP_NO
ORDER BY e.EMP_NO