-- 코드를 작성해주세요
SELECT SUM(SCORE) AS SCORE, e.EMP_NO, e.EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES e INNER JOIN HR_DEPARTMENT d ON e.DEPT_ID = d.DEPT_ID
                    INNER JOIN HR_GRADE g ON e.EMP_NO = g.EMP_NO
GROUP BY e.EMP_NO
HAVING SUM(SCORE) IN (SELECT MAX(SCORE) AS SCORE
                FROM (SELECT SUM(SCORE) AS SCORE, EMP_NO
                      FROM HR_GRADE
                      GROUP BY EMP_NO) temp)