-- 코드를 입력하세요
SELECT FILE_PATH
FROM (SELECT '/home/grep/src/' || b.BOARD_ID || '/' || FILE_ID || FILE_NAME || FILE_EXT AS FILE_PATH, FILE_ID
      FROM USED_GOODS_BOARD b INNER JOIN USED_GOODS_FILE f ON b.BOARD_ID = f.BOARD_ID
      WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD b INNER JOIN USED_GOODS_FILE f ON b.BOARD_ID = f.BOARD_ID)
      ORDER BY VIEWS DESC)
ORDER BY FILE_ID DESC